"""Initial schema.

The whole schema in one revision. Folio had no database in the field when
Alembic was introduced, so there was no create_all-era schema to migrate from --
an incremental chain would have created Float money columns purely so a later
revision could convert them to integer cents. Autogenerated from the models so
it matches them exactly.

Revision ID: 0001
Revises: None
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('CHECKING', 'SAVINGS', 'CREDIT_CARD', 'MORTGAGE', 'VEHICLE_LOAN', 'INVESTMENT', 'OTHER_ASSET', 'OTHER_LIABILITY', name='accounttype'), nullable=False),
    sa.Column('institution', sa.String(length=100), nullable=True),
    sa.Column('account_number_mask', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('current_balance_cents', sa.Integer(), nullable=False),
    sa.Column('credit_limit_cents', sa.Integer(), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('loan_origination_date', sa.DateTime(), nullable=True),
    sa.Column('loan_term_months', sa.Integer(), nullable=True),
    sa.Column('loan_original_principal_cents', sa.Integer(), nullable=True),
    sa.Column('monthly_payment_cents', sa.Integer(), nullable=True),
    sa.Column('escrow_payment_cents', sa.Integer(), nullable=True),
    sa.Column('compounding', sa.Enum('MONTHLY', 'SEMI_ANNUAL', name='loancompounding'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budgets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('total_income_target_cents', sa.Integer(), nullable=False),
    sa.Column('total_expense_target_cents', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='uq_budget_year_month')
    )
    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('type', sa.Enum('INCOME', 'EXPENSE', 'TRANSFER', name='categorytype'), nullable=False),
    sa.Column('is_budgeted', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('securities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('asset_class', sa.Enum('EQUITY', 'ETF', 'MUTUAL_FUND', 'FIXED_INCOME', 'CASH', 'CRYPTO', 'OTHER', name='assetclass'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('securities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_securities_symbol'), ['symbol'], unique=True)

    op.create_table('account_balance_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('balance_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'as_of_date', name='uq_snapshot_account_date')
    )
    with op.batch_alter_table('account_balance_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_balance_snapshots_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_balance_snapshots_as_of_date'), ['as_of_date'], unique=False)
        batch_op.create_index('ix_snapshots_date_account', ['as_of_date', 'account_id'], unique=False)

    op.create_table('budget_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('budget_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('planned_amount_cents', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('budget_id', 'category_id', name='uq_budget_item_budget_category')
    )
    with op.batch_alter_table('budget_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_items_budget_id'), ['budget_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_items_category_id'), ['category_id'], unique=False)

    op.create_table('categorization_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('pattern_type', sa.Enum('EXACT', 'CONTAINS', 'REGEX', 'STARTS_WITH', name='rulepatterntype'), nullable=False),
    sa.Column('pattern', sa.String(length=255), nullable=False),
    sa.Column('min_amount_cents', sa.Integer(), nullable=True),
    sa.Column('max_amount_cents', sa.Integer(), nullable=True),
    sa.Column('target_account_id', sa.String(length=36), nullable=True),
    sa.Column('normalized_payee_override', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categorization_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categorization_rules_category_id'), ['category_id'], unique=False)

    op.create_table('holdings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('security_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'security_id', name='uq_holding_account_security')
    )
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holdings_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_holdings_security_id'), ['security_id'], unique=False)

    op.create_table('investment_activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('security_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.Enum('BUY', 'SELL', 'DIVIDEND', 'CONTRIBUTION', 'WITHDRAWAL', 'FEE', name='investmentactivitytype'), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('fee_cents', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investment_activities', schema=None) as batch_op:
        batch_op.create_index('ix_activity_account_date', ['account_id', 'trade_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_investment_activities_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investment_activities_security_id'), ['security_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investment_activities_trade_date'), ['trade_date'], unique=False)

    op.create_table('price_quotes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('security_id', sa.String(length=36), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id', 'as_of_date', name='uq_quote_security_date')
    )
    with op.batch_alter_table('price_quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_quotes_as_of_date'), ['as_of_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_quotes_security_id'), ['security_id'], unique=False)
        batch_op.create_index('ix_quotes_security_date', ['security_id', 'as_of_date'], unique=False)

    op.create_table('statement_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('holding_id', sa.String(length=36), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('cost_basis_cents', sa.Integer(), nullable=False),
    sa.Column('fee_cents', sa.Integer(), nullable=False),
    sa.Column('closed_quantity', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lots_holding_id'), ['holding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lots_trade_date'), ['trade_date'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('transfer_transaction_id', sa.String(length=36), nullable=True),
    sa.Column('statement_file_id', sa.String(length=36), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('posted_date', sa.DateTime(), nullable=True),
    sa.Column('raw_payee', sa.String(length=255), nullable=False),
    sa.Column('normalized_payee', sa.String(length=255), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('import_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CLEARED', 'RECONCILED', name='transactionstatus'), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['statement_file_id'], ['statement_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transfer_transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('ix_transactions_account_date', ['account_id', 'transaction_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_account_id'), ['account_id'], unique=False)
        batch_op.create_index('ix_transactions_account_import_hash', ['account_id', 'import_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_import_hash'), ['import_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_normalized_payee'), ['normalized_payee'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_date'), ['transaction_date'], unique=False)

    op.create_table('transaction_splits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction_splits', schema=None) as batch_op:
        batch_op.create_index('ix_splits_transaction_category', ['transaction_id', 'category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_splits_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_splits_transaction_id'), ['transaction_id'], unique=False)



def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('transaction_splits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_splits_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_splits_category_id'))
        batch_op.drop_index('ix_splits_transaction_category')

    op.drop_table('transaction_splits')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_normalized_payee'))
        batch_op.drop_index(batch_op.f('ix_transactions_import_hash'))
        batch_op.drop_index('ix_transactions_account_import_hash')
        batch_op.drop_index(batch_op.f('ix_transactions_account_id'))
        batch_op.drop_index('ix_transactions_account_date')

    op.drop_table('transactions')
    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lots_trade_date'))
        batch_op.drop_index(batch_op.f('ix_lots_holding_id'))

    op.drop_table('lots')
    op.drop_table('statement_files')
    with op.batch_alter_table('price_quotes', schema=None) as batch_op:
        batch_op.drop_index('ix_quotes_security_date')
        batch_op.drop_index(batch_op.f('ix_price_quotes_security_id'))
        batch_op.drop_index(batch_op.f('ix_price_quotes_as_of_date'))

    op.drop_table('price_quotes')
    with op.batch_alter_table('investment_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investment_activities_trade_date'))
        batch_op.drop_index(batch_op.f('ix_investment_activities_security_id'))
        batch_op.drop_index(batch_op.f('ix_investment_activities_account_id'))
        batch_op.drop_index('ix_activity_account_date')

    op.drop_table('investment_activities')
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holdings_security_id'))
        batch_op.drop_index(batch_op.f('ix_holdings_account_id'))

    op.drop_table('holdings')
    with op.batch_alter_table('categorization_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categorization_rules_category_id'))

    op.drop_table('categorization_rules')
    with op.batch_alter_table('budget_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_items_category_id'))
        batch_op.drop_index(batch_op.f('ix_budget_items_budget_id'))

    op.drop_table('budget_items')
    with op.batch_alter_table('account_balance_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshots_date_account')
        batch_op.drop_index(batch_op.f('ix_account_balance_snapshots_as_of_date'))
        batch_op.drop_index(batch_op.f('ix_account_balance_snapshots_account_id'))

    op.drop_table('account_balance_snapshots')
    with op.batch_alter_table('securities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_securities_symbol'))

    op.drop_table('securities')
    op.drop_table('categories')
    op.drop_table('budgets')
    op.drop_table('accounts')
