"""account balance snapshots

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-25 21:37:28.793742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: Union[str, Sequence[str], None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_balance_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'as_of_date', name='uq_snapshot_account_date')
    )
    with op.batch_alter_table('account_balance_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_balance_snapshots_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_balance_snapshots_as_of_date'), ['as_of_date'], unique=False)
        batch_op.create_index('ix_snapshots_date_account', ['as_of_date', 'account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_balance_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshots_date_account')
        batch_op.drop_index(batch_op.f('ix_account_balance_snapshots_as_of_date'))
        batch_op.drop_index(batch_op.f('ix_account_balance_snapshots_account_id'))

    op.drop_table('account_balance_snapshots')
    # ### end Alembic commands ###
