"""loan compounding convention

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-25 21:40:24.609324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: Union[str, Sequence[str], None] = "0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default is required: without it, adding a NOT NULL column to a table
    # that already has rows fails.
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "compounding",
                sa.Enum("MONTHLY", "SEMI_ANNUAL", name="loancompounding"),
                nullable=False,
                server_default="MONTHLY",
            )
        )

    # Canadian fixed-rate mortgages are compounded semi-annually, not in advance
    # (Interest Act, s.6). Existing mortgages were being amortized with the US
    # monthly convention, which overstates interest; correct them. Users holding a
    # US mortgage can switch the account back to MONTHLY.
    op.execute("UPDATE accounts SET compounding = 'SEMI_ANNUAL' WHERE type = 'MORTGAGE'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('compounding')

    # ### end Alembic commands ###
