"""investment holdings and performance

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-25 21:58:12.554987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: Union[str, Sequence[str], None] = "0004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('securities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('asset_class', sa.Enum('EQUITY', 'ETF', 'MUTUAL_FUND', 'FIXED_INCOME', 'CASH', 'CRYPTO', 'OTHER', name='assetclass'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('securities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_securities_symbol'), ['symbol'], unique=True)

    op.create_table('holdings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('security_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'security_id', name='uq_holding_account_security')
    )
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holdings_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_holdings_security_id'), ['security_id'], unique=False)

    op.create_table('investment_activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('security_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.Enum('BUY', 'SELL', 'DIVIDEND', 'CONTRIBUTION', 'WITHDRAWAL', 'FEE', name='investmentactivitytype'), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('fee_cents', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investment_activities', schema=None) as batch_op:
        batch_op.create_index('ix_activity_account_date', ['account_id', 'trade_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_investment_activities_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investment_activities_security_id'), ['security_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investment_activities_trade_date'), ['trade_date'], unique=False)

    op.create_table('price_quotes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('security_id', sa.String(length=36), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id', 'as_of_date', name='uq_quote_security_date')
    )
    with op.batch_alter_table('price_quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_quotes_as_of_date'), ['as_of_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_quotes_security_id'), ['security_id'], unique=False)
        batch_op.create_index('ix_quotes_security_date', ['security_id', 'as_of_date'], unique=False)

    op.create_table('lots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('holding_id', sa.String(length=36), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('cost_basis_cents', sa.Integer(), nullable=False),
    sa.Column('fee_cents', sa.Integer(), nullable=False),
    sa.Column('closed_quantity', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lots_holding_id'), ['holding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lots_trade_date'), ['trade_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lots_trade_date'))
        batch_op.drop_index(batch_op.f('ix_lots_holding_id'))

    op.drop_table('lots')
    with op.batch_alter_table('price_quotes', schema=None) as batch_op:
        batch_op.drop_index('ix_quotes_security_date')
        batch_op.drop_index(batch_op.f('ix_price_quotes_security_id'))
        batch_op.drop_index(batch_op.f('ix_price_quotes_as_of_date'))

    op.drop_table('price_quotes')
    with op.batch_alter_table('investment_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investment_activities_trade_date'))
        batch_op.drop_index(batch_op.f('ix_investment_activities_security_id'))
        batch_op.drop_index(batch_op.f('ix_investment_activities_account_id'))
        batch_op.drop_index('ix_activity_account_date')

    op.drop_table('investment_activities')
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holdings_security_id'))
        batch_op.drop_index(batch_op.f('ix_holdings_account_id'))

    op.drop_table('holdings')
    with op.batch_alter_table('securities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_securities_symbol'))

    op.drop_table('securities')
    # ### end Alembic commands ###
