"""lookup indexes

Revision ID: 0006
Revises: 0005
Create Date: 2026-08-25 22:10:03.601237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: Union[str, Sequence[str], None] = "0005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_splits', schema=None) as batch_op:
        batch_op.create_index('ix_splits_transaction_category', ['transaction_id', 'category_id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('ix_transactions_account_import_hash', ['account_id', 'import_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_account_import_hash')

    with op.batch_alter_table('transaction_splits', schema=None) as batch_op:
        batch_op.drop_index('ix_splits_transaction_category')

    # ### end Alembic commands ###
